# Site settings
title: Erin's Isle GAA Club
email: website@erinsislegaa.com
url: "https://mickod.ie"
baseurl: "/freelancer-theme.github.io"
description: "The pride of Finglas since 1917"
keywords: "erinsislegaa erinsisle Finglas Dublin11 Farnham hurling football camogie lgfa"
skills: "Hurling - Camogie - Ladies Gaelic Football - Gaelic Football"
meta_author: Erinsisle2020

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
# disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Erin's Isle GAA Club
  location: Dublin, Ireland
  social: Socials
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/theislesclg
  - title: facebook
    url: https://facebook.com/erinsisle
      #  - title: github
      #url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Farnham Drive, Finglas
  - line: Dublin, D11 RRK6

# Credits content
credits: 'The template for this website is based on *Freelancer* which is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
